AllCops:
  TargetRubyVersion: 2.0

AllCops:
  Exclude:
    - examples/*
    - spec/*

# Disables "Use nested module/class definitions instead of compact style" warning
ClassAndModuleChildren:
  Enabled: false

# Increases "Class definition is too long" warning from 100 to 200
Metrics/ClassLength:
  Max: 200

# Increases "Method has too many lines" warning from 10 to 75
Metrics/MethodLength:
  Max: 75

# Increases "Module has too many lines" warning from 100 to 300
Metrics/ModuleLength:
  Max: 300

# Increases "Assignment Branch Condition size" warning from 15 to 80
Metrics/AbcSize:
  Max: 80

# Increases "Block has too many lines" warning from 25 to 190
Metrics/BlockLength:
  Max: 190

# Disables "Missing top-level class documentation comment" warning
Documentation:
  Enabled: false

# Increases "Line is too long" warning from 80 tp 200
Metrics/LineLength:
  Max: 200
  Enabled: true

CyclomaticComplexity:
  Enabled: false

PerceivedComplexity:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact

Layout:
  Enabled: False

RescueWithoutErrorClass:
  Enabled: False

