# .travis.yml
language: ruby

sudo: required
bundler_args: --retry=3 --jobs=3

rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4

before_install:
  - gem install bundler
  - gem update bundler

script: bundle exec rspec spec || true

fast_finish: true

gemfile:
  - Gemfile

