# .travis.yml
language: ruby

sudo: required
bundler_args: --retry=3 --jobs=3

rvm:
  - 2.3
  - 2.4
  - 2.5

before_install:
  - gem install bundler
  - gem update bundler
  - docker pull bodsch/docker-grafana:5.4.3
  - |
    docker run \
    --rm \
    --detach \
    --publish=3030:3000 \
    --env URL_PATH=/ \
    --hostname=grafana \
    bodsch/docker-grafana:5.4.3
  - docker ps
  - sleep 20s

script: bundle exec rspec spec

fast_finish: true

gemfile:
  - Gemfile
